### ISSUE TITLE
请问使用pure后如何结合使用第三方插件，比如jquery-ui

### ISSUE THREAD

**Issue by fancyboynet** [fex-team/fis-pure#11]
现在我的项目jquery已经是在modules目录下当典型的fis模块来用了，现在要用到jquery-ui插件，jquery-ui.js又是amd，依赖的又是全局下的jquery对象，这时该如何处理呢？我不想修改第三方的插件，还是我直接全局引入jquery？会不会产生两次加载jquery了？

**Comment by hefangshi** [comment]
可以考虑直接加载jquery，不要当成模块来处理，自己的业务代码使用模块化管理就可以了

**Comment by fancyboynet** [comment]
我自己的模块都是依赖模块的jquery了，考虑第三方插件不会经常变动，所以我还是选择了修改插件了...
