### ISSUE TITLE
异步加载模块时css不异步的问题

### ISSUE THREAD

**Issue by xxapp** [fex-team/fis-pure#12]
同一个模块下有xxx.js  xxx.tmpl   xxx.css这三个文件。
使用require.async('/app/xxx')异步加载，到这里都是正常的。

但是我发现没有进行异步加载之前，xxx.css就被link在页面中了。
望请指点。

**Comment by xiangshouding** [comment]
我想你说的是 js，css异步不做特殊处理是无法异步的。

FIS 里面有个同名依赖规则，当 js、css 的名和 html 相同时，会默认同步加载这些文件。不管你是否用了异步语句加载这个文件。

**Comment by xxapp** [comment]
噢，同名处理以前我也很奇怪怎么回事。
如果想异步加载css怎么做？

**Comment by hefangshi** [comment]
pure没有提供异步加载css的能力，即使是异步脚本里面声明的CSS依赖也会同步加载进来。

主要原因就是CSS异步加载通常来说是得不偿失的，容易造成重绘和页面闪动，而异步CSS带来的性能提升在大部分场景都比较有限。

如果想异步加载CSS，可以考虑将CSS wrap为js后加载

https://github.com/hefangshi/fis-prepackager-csswrapper

**Comment by xxapp** [comment]
感谢回答，问题已经解决
