### ISSUE TITLE
pure合并CSS失败，是能合并JS模块

### ISSUE THREAD

**Issue by ioriandy4** [fex-team/fis-pure#17]
用的是官方的fis-pure-demo，合并压缩，想CSS也跟着合并压缩，所以配置如下：

```js
fis.config.set('modules.postpackager', 'simple');
fis.config.set('pack', {
    'pkg/lib.js': [
        '/modules/**.js'
    ],
    'pkg/aa.css':[
    	'**.css'
    ]
});
```

结果合并失败了，，在html里面没有连接进去任何CSS，而且提示报错,请问怎么配置才可以连模块的css也一起合并啊

**Comment by hefangshi** [comment]
我这边并没有什么报错，另外整个demo就一个app.less，你是要合并什么呢？

提issue的正确姿势是尽可能的详细的描述状况

比如你说html里面没有连接进去任何CSS，请把源代码和pure产出的HTML贴出来

比如你说提示报错，是编译的时候报错还是页面加载的时候报错，要说清楚，报了什么错，贴出来

这样才能减少沟通成本，节约大家的时间。

最后，`fis-pure` 是有很多人使用的解决方案，CSS合并这类基础功能不太可能出问题。
