### ISSUE TITLE
为什么官方的pure的demo里面，没有引用app.less，但合并压缩后却在html自动加上了

### ISSUE THREAD

**Issue by ioriandy4** [fex-team/fis-pure#18]
为什么官方的pure的demo  fis-pure-demo-master里面，我查找过没有文件引用了app.less，但合并压缩后却在html自动编译成app.css，还连接进去了？

**Comment by hefangshi** [comment]
因为引用了app.js, app.less作为同名依赖，会被自动引用

**Comment by ioriandy4** [comment]
那pure有没有办法解除这种依赖呢？

**Comment by hefangshi** [comment]
不能，有需要的话你可以加一些后缀，比如app.inline.css，这样就不会被自动依赖了。

2015-05-16 15:20 GMT+08:00 ioriandy4 <notifications@github.com>:

> 那pure有没有办法解除这种依赖呢？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fex-team/fis-pure/issues/18#issuecomment-102583223>.
>



-- 
Your Truly,
He
