### ISSUE TITLE
二级目录下的HTML似乎没有被分析处理

### ISSUE THREAD

**Issue by notxx** [fex-team/fis-pure#21]
一级目录下的HTML被分析了，对js和css的引用都会被替换，但是二级目录下的HTML还是原始的引用，因为没有md5的后缀，引用都是失效的。应该怎么配置？

**Comment by hefangshi** [comment]
不太可能存在这种情况，请把情况描述的更详细一些，最好带上DEMO

怀疑是你的路径没有按照源文件代码结构来写

**Comment by notxx** [comment]
我的静态文件都是放在webroot 下的，这个目录里的HTML被分析替换了，但是webroot的子目录下的HTML就没有分析替换，release出来就链接不到js和css。

**Comment by hefangshi** [comment]
听你说webroot估计就有哪里出现很大的理解偏差了吧

把你的源代码结构发出来看看

**Comment by notxx** [comment]
大概是
webroot
  user
  admin
  css
  js

webroot里的HTML文件都和文档里说的一样，user和admin就没处理了

**Comment by hefangshi** [comment]
你的`fis-conf.js`在哪里？你又是如何将源代码发布到后端服务器上的？

**Comment by notxx** [comment]
fis-conf.js在webroot的父目录下，用pure release -mp --dest output来做输出。如果我把fis-conf.js放webroot会好吗？

**Comment by hefangshi** [comment]
没关系，那么你webroot里面是如何引用的js和css文件的，上几个代码示例

**Comment by notxx** [comment]
就是HTML的标准用法，<link rel="stylesheet" href="...">和<script src="...">，然后在fis-conf.js里面用autoCombine自动合并来着。

**Comment by hefangshi** [comment]
睡觉了~切记你应该写源代码路径，就以你的目录结构为例

webroot/index.html中对js的引用路径应该为

```html
<script src="../js/index.js"></script>
```

或者使用绝对路径

```html
<script src="/js/index.js"></script>
```

而 webroot 下的二级目录 webroot/user/index.html 中，则应该使用

```html
<script src="../../js/index.js"></script>
```

或者使用绝对路径，绝对路径的话，和目录层级无关。

```html
<script src="/js/index.js"></script>
```

**Comment by hefangshi** [comment]
不过你这样的用法何必使用 `pure` ，直接使用 `fis` 就好了。

**Comment by notxx** [comment]
难道是不支持[base href="/"]这个写法的？

**Comment by hefangshi** [comment]
没听说过什么 `[base href]`

**Comment by notxx** [comment]
原来fis的根是以fis-conf.js所在位置而言的，这个行为是可以更改的吗？可能个人不是太喜欢把服务器端文件和客户端文件混在一起。
另外`<base href="/">`这个标签不支持似乎是缺少特性了，准备去fis工程提个issue

**Comment by hefangshi** [comment]
`base`这样的标签是无法被支持的。

你说的 `base` 的功能，都可以通过 FIS 构建来解决，另外你说的 `太喜欢把服务器端文件和客户端文件混在一起` 说明你对 `FIS` 的开发理念理解有偏差。

不过还没有理解你具体是怎么想的，你是认为 `webroot` 中的文件是服务端文件是么？

**Comment by notxx** [comment]
`base`标签的功能不是让其他有`href`或者`src`的标签可以写短一些么？并不改变链接本身是相对还是绝对的性质啊，你们的一些文档里的说绝对路径是没问题的。

我是觉得webroot下都是客户端文件，浏览器随便下载。虽说fis-conf.js被下载了看似也不会有什么危害，但是总觉得不好。

**Comment by hefangshi** [comment]
知道你错误理解的地方在哪了。

在 `FIS` 的工作流程中，是有这样几个角色的

- 源代码
- 编译产出
- 测试环境
- 生产环境

`fis-conf.js` 只会存在在源代码中，而你说的 `fis-conf.js` 会被下载是因为你是把整个源代码直接放在生产环境中了。

正确的做法是在源代码管理器中维护源代码，通过 `FIS` 编译后获得编译产出，将编译产出部署至测试环境和生产环境。

**Comment by notxx** [comment]
可能你说的没错，我再适应适应

**Comment by hefangshi** [comment]
不知道你现在是怎么用的，源代码和产出目录是不能放在一起的，否则产出目录中压缩后的文件就会覆盖源代码中的文件，这样就导致源代码无法再次修改。

**Comment by notxx** [comment]
之前我是直接用源代码目录里的webroot，现在用fis产出到output。主要是其他目录里还有服务器端脚本，也想用fis管理，所以有点乱。

**Comment by hefangshi** [comment]
没看到你这个目录结构中有服务端脚本，使用 `FIS` 的一个推荐做法是把前后端代码分离开，只用 `FIS` 处理前端代码。

在 2015年6月16日 上午11:01，notxx <notifications@github.com>写道：

> 之前我是直接用源代码目录里的webroot，现在用fis产出到output。主要是其他目录里还有服务器端脚本，也想用fis管理，所以有点乱。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fex-team/fis-pure/issues/21#issuecomment-112266998>.
>



-- 
Your Truly,
He

**Comment by notxx** [comment]
好的。
另外有个问题，我的有些js是独立工程管理的，用submodule的方式引入当前工程，然后用符号链接放到webroot下，但是fis对这个方式也有特殊的处理？提示`unreleasable`，是说这个文件在处理范围之外所以不能处理？

**Comment by hefangshi** [comment]
不支持软链，FIS 实现的是整站资源的整体编译，所以要求整个项目引用的资源都在项目内。

**Comment by notxx** [comment]
但是实际上资源并不是不在项目内，只是因为submodule这种方式所以位置有不同啊。fis本身还不是空空荡荡完全靠插件的。

**Comment by hefangshi** [comment]
把 FIS 和前端项目比较并不合适吧。

关于软链的使用的确是一个有争议的话题，由于 FIS 诞生于百度内部，第一目标是服务好内部产品线，为了解决代码管理混乱的问题，把软链去掉了，因为在这个上面踩过坑。

不知道你说的submodule是否是git的submodule，如果是的话，你先安装下载进来，并不需要软链。
