### ISSUE TITLE
release后,JS也被加在html的head中。html声明依赖后如何不添加 JS？

### ISSUE THREAD

**Issue by xianglgd** [fex-team/fis-pure#24]
如题，如何解决？
问题1：
我 modules 下 有个 app 文件夹，其中有 app.js， app.css。
外面index.html ，采用 require("app"); 编译后，会把 app.js放在 head中。
可是我想放在 body 底部呀 。怎么做呢？

问题2：
我在 HTML中声明一个 依赖 @require lib/mod.js。 编译后就把 JS 放入head 中。
我想要的是，声明依赖，编译后只是产生 map.json，不把JS添加入 head中。
如何做？

**Comment by hefangshi** [comment]
问题1

fis-pure 中是使用 https://github.com/hefangshi/fis-postpackager-autoload 注入脚本，因此控制脚本输出位置的功能可以参考 autoload 插件的配置

问题 2

lib/mod.js作为模块化的基础加载库，是不能异步加载的，必须将JS添加进head中，你如果希望某些资源是异步加载，可以使用 `require.async`

**Comment by xianglgd** [comment]
问题一可以解决，，，
问题二 我 换个问法。
我在 HTML中声明一个 依赖 @require modules/head/head.js。 编译后就把 JS 放入head 中。
我想要的是，声明依赖，编译后只是产生 map.json，不把JS添加入 head中。
如何做？

**Comment by hefangshi** [comment]
不使用autoload插件就可以，不过你为何会有这种需求

**Comment by xianglgd** [comment]
谢谢，，我去了解下 autoload插件。

**Comment by xianglgd** [comment]
- -，，，，不好意思呀，，，我找遍了 fis-config 都没找到在哪个地方使用了  autoload插件。
  这个插件应该是自动使用的吧？  
  我是应该设置什么，然后告诉 fis 不适用该插件吧？

**Comment by hefangshi** [comment]
你不用autoload，不如就直接用fis呀，为何还要用fis-pure呢？

```
fis.config.set('modules.postpackager', 'simple');
```

这样就可以关闭 autoload 了

**Comment by xianglgd** [comment]
谢谢，，，，，
