### ISSUE TITLE
require.async ，传入一个变量，不会产生map.js

### ISSUE THREAD

**Issue by xianglgd** [fex-team/fis-pure#25]
HTML 中 require.async("app/main"); 编译后，会把 app/ 下同名的CSS 放入 head中。并且head中放入 一个map.js。内容是这样的。
require.resourceMap({
"res": {
"app": {
"url": "/static/modules/app/app.js"
},
"app/main": {
"deps": [
"app"
],
"url": "/static/modules/app/main.js"
}
},
"pkg": {}
});
但是如果 我是 a="app/main"; require.async(a); 就会不会产生map.js ，于是require时就会报错。

PS： 怎么 编译后 JS都在头部呀？ 我想放在最底部呀。。。。。。。。。

**Comment by hefangshi** [comment]
require.async 中不能直接使用变量，如果希望使用变量，需要用注释的形式声明变量可能取的值

```
<!-- @require.async app/main -->
```

**Comment by xianglgd** [comment]
哦，，，，，多个取值 怎么分开？
空格吗？
<!-- @require.async app/main  head/main -- >
这样？

**Comment by hefangshi** [comment]
```
<!-- 
    @require.async app/main
    @require.async head/main
-->
```

**Comment by xianglgd** [comment]
我这样试了，，，，不行呀，，还是没产出 map.js ，
