### ISSUE TITLE
安装了pure之后无法使用pure指令！

### ISSUE THREAD

**Issue by sabver** [fex-team/fis-pure#33]
执行的指令如下：
npm install -g pure
pure -v
这时就报错：
'pure' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

附上安装目录截图：
![image](https://cloud.githubusercontent.com/assets/6829063/11836362/4033d16a-a415-11e5-8d02-e357c70e571f.png)
可以看到，外面并没有pure这个文件存在，
到里面：
![image](https://cloud.githubusercontent.com/assets/6829063/11836373/50b0983e-a415-11e5-89aa-c7286c21c890.png)
里面的确存在pure的安装文件
请问这个问题改如何解决？

**Comment by hefangshi** [comment]
```
npm i -g fis-pure
```

不是 pure

另外，建议直接使用 fis3

**Comment by sabver** [comment]
![image](https://cloud.githubusercontent.com/assets/6829063/11836871/5d2817f6-a418-11e5-8aea-f6f156ad09cf.png)

请问fis3怎么实现自动合并页面的零碎资源？

**Comment by hefangshi** [comment]
https://github.com/fex-team/fis3-postpackager-loader
