### ISSUE TITLE
Less文件和csssprites有冲突？

### ISSUE THREAD

**Issue by sunxjie** [fex-team/fis-pure#8]
项目里使用纯CSS的方式，csssprites执行正常，会生成合并的图片，Less文件就不行，求解？
配置里这样写的：
{
                //其他css文件
                reg : /^(.*)\.(css|less)$/i,
                useSprite: true,
               	release : '${statics}/$&'
            }

**Comment by hefangshi** [comment]
配置看起来没什么问题，方便的话可以发个DEMO的github repo看看，如果你确认图片路径以及 ```?__sprite``` 已经正确添加

**Comment by sunxjie** [comment]
谢谢！！
问题解决了，汗...  是图片路径的问题，我用的是发布后的路径。
